# Variables
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck

GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom

POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "New Room",
    "description": "This is a new room created via HTTP client."
}


###

@roomId = {{createRoom.response.body.$.roomId}}


###

# Get Room Questions
# @name getRoomQuestions

GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Question
# @name createQuestion

POST {{baseUrl}}/rooms/e7b2874d-f52c-4b14-9b2e-ee8ca30b83f6/questions
Content-Type: application/json

{
    "question": "Me diga sobre o jogo Hitman"
}